Update getting-started.md
Vimux/Mainroad pull request #285
Opened 2022-02-22 22:40 UTC by lisa005

Edits for grammar, clarity, and conciseness. Updated the Customization page link.

2022-02-23 17:40 UTC, Vimux requested changes

2022-02-23 22:08 UTC, lisa005 commented on exampleSite/content/docs/getting-started.md
> +by downloading the archive and manually copying the files. The three recommended
Got it! Makes sense.

2022-02-23 22:13 UTC, lisa005 commented on exampleSite/content/docs/getting-started.md
> -and check that theme works. Only then start to add theme-specific parameters that you really need.
Sounds good! Will update.

2022-02-23 22:15 UTC, lisa005 commented on exampleSite/content/docs/getting-started.md
> +To view our example configuration, visit [demo config](https://github.com/vimux/mainroad/blob/master/exampleSite/config.toml). For information about common customization settings, see [Customization]
Apologies, will do.

2022-02-23 22:50 UTC, lisa005 commented on exampleSite/content/docs/getting-started.md
> +Welcome to the Mainroad theme documentation. This quick start guide covers Mainroad theme installation and minimal configuration and is intended for intermediate
Okay, thanks for the info. I tried to go through and edit the lines exceeding this max.

2022-02-25 13:05 UTC, Vimux reviewed
One more thing: trim single spaces at the end of lines.

Example: 
![Screen Shot 2022-02-25 at 07 51 37](https://user-images.githubusercontent.com/21033483/155719608-a0a9db91-1071-48b2-997b-ceefa567ee80.png)

2022-02-25 18:21 UTC, merged

2022-02-25 18:21 UTC, Vimux commented
@lisa005,

Thank you for your help.