Due to deprecated .Site.Author taxonomy should be used
Vimux/Mainroad pull request #379
Opened 2024-10-09 18:25 UTC by JuliusLongmind

Hi There!

With the last version hugo it seems .Site.Author is deprecated and .Site.Params.Author should be used.

I hope it helps,
Julius Longmind

2024-10-25 21:32 UTC, jonatan-ivanov commented
On Hugo `0.124.0` and above (definitely on `0.136.4`) this actually fails the build (`hugo --gc --minify`):
```
ERROR deprecated: .Site.Author was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Implement taxonomy 'author' or use .Site.Params.Author instead.
```

@Vimux Could you please take a look?

2024-10-25 22:15 UTC, jonatan-ivanov requested changes
I think the documentation (readme) should be also updated and the `Author` section should be moved under `Params`.

2025-02-08 23:29 UTC, Jean85 approved these changes

2026-05-25 19:24 UTC, closed without merging

2026-05-26 19:00 UTC, jonatan-ivanov commented
@JuliusLongmind Did you close this by accident? Or is the change not valid anymore?

2026-05-26 20:23 UTC, JuliusLongmind commented
@jonatan-ivanov  I have just closed it. It is not important anymore.

2026-05-26 20:32 UTC, jonatan-ivanov commented
For you or was it fixed?